language: go
sudo: required

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

services:
  - redis-server

before_install:
  - sudo redis-server /etc/redis/redis.conf -port 7777
  - go get -u github.com/haya14busa/goverage

script:
  - ./test.sh

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - bash <(curl -s https://codecov.io/bash)
